### PR TITLE
Add support for building at OBS 

### PR DESCRIPTION
**Pull request by rinigus**
I have made some changes in YAML/SPEC/PRO to setup OBS builds. Now its possible to build it there.

### CODE REVIEW

**Comment by rinigus** [comment]
The static build of presage library is used now. Note that presage has to be built using -fPIC, as using https://github.com/rinigus/presage/commit/ca3e38aa91df6d1e90bc24a636ead23ee53b033d

The static libs containing presage-devel is available at OBS, by adding repositories https://build.merproject.org/project/repositories/home:rinigus:keyboard (depending on ARCH) to SDK.

**Review by martonmiklos — APPROVED** [review]
LGTM

**Comment by rinigus** [comment]
I'll resolve the conflicts, no problem. Thanks for uploading the latest version :) . Just give me a little bit of time and I'll push the resolved version.

**Comment by rinigus** [comment]
:) you were faster!

**Pull request merged**
