### PR TITLE
Set Marisa-based predictor as default 

### PR DESCRIPTION
**Pull request by rinigus**
This PR introduces Marisa Trie based predictor as a main predictor for presage. Together with the recent changes in https://github.com/rinigus/presage , it allows to 

* build language databases in Marisa-based format and package them for SFOS. See https://github.com/rinigus/presage/blob/master/README.md for instructions and packaging script

* build keyboard packages for SFOS using a script provided under utils/keyboard directory. Corresponding README.md is provided in the same directory with instructions.

* uses DefaultSmoothedNgramTriePredictor to set the predictor's dictionary

* renames the plugin into maliit-plugin-presage

I have introduced new names for the packages as discussed in https://github.com/martonmiklos/sailfishos-presage-predictor/issues/18 . This was done already here to make keyboard RPM require maliit-plugin-presage.

Currently, the plugin expects configuration as provided by `presage-data` from http://repo.merproject.org/obs/home:/rinigus:/keyboard/sailfish_latest_armv7hl/armv7hl/ (or similar repo for i486). As discussed in  https://github.com/martonmiklos/sailfishos-presage-predictor/issues/18 , we'll merge presage-data provided config into the package of maliit-plugin-presage and avoid presage-data. I may add that tomorrow night as a separate PR or here (if not merged by that time).

Note that RPMs in OBS are all compiled with this PR functionality allowing you to test it on device as soon as the keyboard and database is ready for Hungarian or English.

### CODE REVIEW

**Comment by martonmiklos** [comment]
Great job!

**Comment by rinigus** [comment]
I have added now /etc/presage.xml and an empty database under /usr/share/presage/database_empty.

This should obsolete presage-data and would make installation rather simple: users need the plugin, dictionary, and keyboard. No more libs or extra data files. As such, this PR should resolve all issues raised in https://github.com/martonmiklos/sailfishos-presage-predictor/issues/18

**Comment by rinigus** [comment]
@martonmiklos , have you had a chance to test this pull request? I have updated installation and usage instructions at https://build.merproject.org/project/show/home:rinigus:keyboard which should allow you to test the keyboard in English. If you wish, I can convert your Hungarian dictionary into MARISA format as well.

**Comment by martonmiklos** [comment]
Ah, I have not been able to get to the point when I can test it. If you could convert the Hungarian ngram to marisa that would be great. Do you need text corpus or the SQLite is appropriate?

**Comment by rinigus** [comment]
SQLite is fine. I guess, I'll pull it from OpenRepos, that should be fine. I'll fetch Swedish as well. I'll ping you when its ready

**Comment by rinigus** [comment]
Hungarian and Swedish languages are converted to MARISA and available at  https://build.merproject.org/project/show/home:rinigus:keyboard . I haven't done keyboards since those are trickier with arrowboard. However, you could probably use your current keyboards if you just replace presage stack

To make it work, you would need to uninstall all presage packages except keyboards. Then install packages

* `maliit-plugin-presage` from http://repo.merproject.org/obs/home:/rinigus:/keyboard/sailfish_latest_armv7hl/armv7hl/

* favorite languages from http://repo.merproject.org/obs/home:/rinigus:/keyboard/sailfish_latest_armv7hl/noarch/

Keyboard should have restarted with the installation of the plugin. Choose the keyboards in Settings (maybe needed since you were wiping packages away before) and try.

As you could see, current SV and HU packages are the smallest ones. This tells you that you could easily increase your databases by 2-3 or even probably more times.

CC @ljo

**Comment by ljo** [comment]
@rinigus Thanks, yes, I experimented a lot to get small enough sizes that gave snappy performance on choosing the suggestions early rather than waiting for more keys being pressed on the keyboard (slower). I will find better sizes suitable for the new conditions/opportunities with Marisa.

**Comment by rinigus** [comment]
Hi! How is it going with the testing? I am finishing the first writeup with ASYNC presage calls and would probably be ready to submit for merging in few days (if all goes as planned). Would be good to get this PR merged by that time, if there are no significant issues with it.

**Comment by rinigus** [comment]
My first test of asynchronous patch is very promising. I don't see any degradation in performance and it seems to work as it should. Which suggests that I maybe able to submit it for review even earlier than I thought :)

Looking forward to your feedback regarding Marisa patch.

**Comment by rinigus** [comment]
Any progress with the review of this PR? Asynchronous presage prediction is ready and waiting for submission. Since I developed it on the top of this one, I need Marisa to be accepted before I can submit the next one.

**Comment by martonmiklos** [comment]
Testing time is on. Which is your preferred source for the libmarisa?

**Comment by rinigus** [comment]
Morning! 

For SFOS, please use https://build.merproject.org/project/show/home:rinigus:toolbox . Its using packaging scripts from https://github.com/rinigus/pkg-marisa and source dump from https://github.com/rinigus/marisa-trie . Easiest is to add (add+refresh) repositories (ARM and i486) of https://build.merproject.org/project/show/home:rinigus:toolbox to SDK and libmarisa will be pulled automatically when you build the module.

For Linux, its frequently packaged by the distribution.

Let me know if anything is missing or there are some complications.

**Comment by martonmiklos** [comment]
Thanks, as a start I wanted to install it on my phone the rpm packages.

**Comment by rinigus** [comment]
In that case, its much easier - get RPMs from http://repo.merproject.org/obs/home:/rinigus:/keyboard/sailfish_latest_armv7hl/armv7hl/

You will need

http://repo.merproject.org/obs/home:/rinigus:/keyboard/sailfish_latest_armv7hl/armv7hl/maliit-plugin-presage-1.0+marisa.20180216195839.37597cb-10.20.1.jolla.armv7hl.rpm

and corresponding packages for keyboard/language support from

http://repo.merproject.org/obs/home:/rinigus:/keyboard/sailfish_latest_armv7hl/noarch/

There is no need to install libmarisa separately since its linked statically. All dependencies of the plugin are shown at https://build.merproject.org/package/binary/home:rinigus:keyboard/sailfishos-presage-predictor?arch=armv8el&filename=maliit-plugin-presage-1.0%2Bmarisa.20180216195839.37597cb-10.20.1.jolla.armv7hl.rpm&repository=sailfish_latest_armv7hl

Hungarian keyboard is not available, please configure it yourself. I think that your current Hungarian presage keyboard should work with the new setup as well.

**Comment by martonmiklos** [comment]
Ah I have missed the fact that the presage is linked statically so at first I wanted to install libpresage which was depending on the libmarisa.

**Comment by rinigus** [comment]
Yes, presage is a forest of different packages. In practice, we need just  libpresage-devel which contains a library for static linking and headers. The rest is side effect of compilation and not needed. Now, when we have in this plugin version data incorporated as well, even presage-data is not needed anymore.

**Comment by ljo** [comment]
@rinigus The testing is on here too since Friday evening. It looks like it required an explicit 
`pkill maliit-server; MALIIT_DEBUG=enabled maliit-server`
to create the user lang files in `~/.local/share/presage/`
with just rebooting it was not working (to get any suggestions, and the local lang files were absent).
BTW the path for user local settings is still `~/.presage/presage.xml`
Thanks for this great work. I look forward to testing the async PR on top of this PR.

**Comment by rinigus** [comment]
@ljo - thanks for testing! 

I would suggest to file the issues for the config files, restarts and I will deal with them a little bit later. I would prefer not to touch these parts in the code until ASYNC will land since otherwise I'll get a lot of conflicts and would have to re-implement ASYNC as well (in async we have plugin split into presage thread and gui interaction class, so it will be a mess to fix it for this implementation).

@ljo, I presume you feel the speedup from Marisa?

**Comment by ljo** [comment]
@rinigus Sure, I just wanted to dump those things somewhere visible. I agree we should definitely merge ASYNC as soon as possible. I do feel the Marisa speed-up. Trying to get a new good balanced assymmetric selection with a larger part of my original dataset, since I am not sure I will mange to make a straight 3-4 times increase of all n-grams without feeling a bit sluggish again.

**Comment by rinigus** [comment]
@ljo, actually, I am pretty sure that you can safely increase it 3-4 times. Marisa should be able to handle it in sync quite well. It stores data differently and worked for me with considerably larger datasets for Estonian and English. 

Although, I agree, I'd like to get this merged ASAP so I can submit ASYNC and start fixing these bugs that you encountered. I have extended Presage by adding Hunspell-based predictor, so I am focusing on making that work now. After that I can deal with the bugs :)

**Comment by ljo** [comment]
@rinigus Let us see where the increse factor ends up.
@martonmiklos For this PR I suggest a merge (since I cannot selfassign) :).

**Comment by martonmiklos** [comment]
Okay let's go down that way. QA will be taken in place before release. :D

**Comment by martonmiklos** [comment]
@rinigus Man you are awesome! It is so freaking fluid that I cannot find any words!

**Comment by rinigus** [comment]
:) thank you! Is it just with Marisa or with asynchronous PR?

**Comment by ljo** [comment]
@rinigus FYI I put the new Swedish Marisa-based language resource package here yesterday [Openrepos Swedish language resource for presage ng](https://openrepos.net/sites/default/files/packages/767/presage-lang-sv-0.2.1-1.noarch.rpm)

**Pull request merged**
